{{- if .Values.traefik.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 36.3.0
    helm:
      releaseName: yke-traefik
      valuesObject:
        gateway:
          listeners:
            websecure:
              port: 8443
              protocol: HTTPS
              namespacePolicy: All
              mode: Terminate
              certificateRefs:
                - name: yoofionline-tls
                  namespace: default
        providers:
          kubernetesIngress:
            enabled: false
          kubernetesGateway:
            enabled: true
        service:
          type: NodePort
  destination:
    name: in-cluster
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
{{- end }}
