{{- if and (eq .Values.provider "aws") .Values.aws.ebsCsiDriver.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.aws.ebsCsiDriver.name }}
  namespace: argocd
spec:
  project: default
  source:
    chart: aws-ebs-csi-driver
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
    targetRevision: {{ .Values.aws.ebsCsiDriver.chartVersion }}
    helm:
      releaseName: yke-aws-ebs-csi-driver
      values: |
        controller:
          serviceAccount:
            create: true
            name: ebs-csi-controller-sa
        node:
          serviceAccount:
            create: true
            name: ebs-csi-node-sa
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
{{- end }}