clusterMetrics:
  enabled: false
  name: cluster-metrics
  namespace: monitoring
  chartVersion: 3.0.2
  releaseName: cluster-metrics
  values:
    cluster:
      name: yoofionprem-cluster
    destinations:
      - name: hosted_metrics
        type: prometheus
        url: "https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push"
        auth:
          type: basic
          usernameKey: grafana-username
          passwordKey: grafana-password
        secret:
          create: false
          name: grafana-secrets
          namespace: monitoring
    clusterMetrics:
      enabled: true
      kube-state-metrics:
        metricsTuning:
          useDefaultAllowList: false
      kubelet:
        metricsTuning:
          useDefaultAllowList: false
      cadvisor:
        metricsTuning:
          useDefaultAllowList: false
    alloy-metrics:
      enabled: true
  
externalSecrets:
  enabled: true

traefik:
  enabled: true

certManager:
  enabled: true

datadog:
  enabled: false
  agent:
    apiKey: ""
    site: ""

# AWS-specific applications
aws:
  ebsCsiDriver:
    enabled: false
    namespace: kube-system
    chartVersion: 2.45.1

# GCP-specific applications
gcp:
  computePersistentDiskCsi:
    enabled: false
    name: gcp-compute-persistent-disk-csi-driver
    namespace: kube-system
    chartVersion: 1.9.0
