apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ybquansah@gmail.com
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-prod-issuer-account-key
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yoofionline-tls
  namespace: default
spec:
  dnsNames:
  - yoofionline.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production
  secretName: yoofionline-tls
  usages:
  - digital signature
  - key encipherment
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: yoofionline-ingress
#   annotations:
#     cert-manager.io/cluster-issuer: letsencrypt
# spec:
#   rules:
#     - host: yoofionline.com
#       http:
#         paths:
#           - path: /
#             pathType: Exact
#             backend:
#               service:
#                 name: echoserver
#                 port:
#                   number: 80
#   tls:
#     - hosts:
#         - yoofionline.com
#       secretName: yoofionline-tls
