apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yoofionline-tls
  namespace: default
spec:
  dnsNames:
  - yoofionline.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: yoofionline-tls
  usages:
  - digital signature
  - key encipherment
