apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: ybquansah@gmail.com
    # The ACME certificate profile
    profile: tlsserver
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: yoofionline-tls
#   namespace: default
# spec:
#   dnsNames:
#   - yoofionline.com
#   issuerRef:
#     group: cert-manager.io
#     kind: ClusterIssuer
#     name: letsencrypt
#   secretName: yoofionline-tls
#   usages:
#   - digital signature
#   - key encipherment
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yoofionline-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: yoofionline.com
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: echoserver
                port:
                  number: 80
  tls:
    - hosts:
        - yoofionline.com
      secretName: yoofionline-tls
