apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: ealen/echo-server:latest
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
  selector:
    app: echoserver
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: echoserver-ingress-route
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    # Rule on the Host
    match: Host(`yke-ingress-7c0d0c36bd54a606.elb.us-east-1.amazonaws.com`)
    services:
    # Target a Kubernetes Support
    - kind: Service
      name: echoserver
      namespace: default
      # Customize the connection between Traefik and the backend
      passHostHeader: true
      port: 80
      responseForwarding:
        flushInterval: 1ms
      strategy: RoundRobin
      weight: 10

