apiVersion: v1
kind: Pod
metadata:
  name: fio-write-test
spec:
  restartPolicy: Never
  volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: ebs-claim
  containers:
    - name: fio
      image: alpine:latest
      command:
        - sh
        - -c
        - |
          apk add --no-cache fio
          echo "Starting fio write test..."
          fio --name=write-test \
              --directory=/data \
              --filename=fio-testfile \
              --size=1G \
              --bs=4k \
              --iodepth=16 \
              --rw=write \
              --ioengine=libaio \
              --direct=1 \
              --numjobs=1 \
              --time_based \
              --runtime=30s \
              --group_reporting
      volumeMounts:
        - name: test-volume
          mountPath: /data
