# This will only work on amd64 architectures
apiVersion: v1
kind: Pod
metadata:
  name: memory-pressure
spec:
  containers:
    - name: stress-memory
      image: polinux/stress
      args:
        - "--vm"
        - "2"
        - "--vm-bytes"
        - "128M"
        - "--vm-hang"
        - "0"
