#cloud-config
write_files:
  - path: /usr/local/bin/init.sh
    permissions: "0755"
    content: |
      sudo apt update
      sudo apt install --yes apache2
      sudo systemctl start apache2
      sudo systemctl enable apache2
runcmd:
  - bash /usr/local/bin/init.sh
