apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.externalSecrets.name }}
  namespace: argocd
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io/ 
    targetRevision: {{ .Values.externalSecrets.chartVersion }}
    helm:
      releaseName: {{ .Values.externalSecrets.releaseName }}
  destination:
    name: in-cluster
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true